TWEAK_NAME = DoABarrelWall
DoABarrelWall_FILES = Tweak.xm
DoABarrelWall_CFLAGS = -fobjc-arc
DoABarrelWall_FRAMEWORKS = UIKit
DoABarrelWall_EXTRA_FRAMEWORKS = Cephei 
DoABarrelWall_LIBRARIES = gcuniversal
ADDITIONAL_CFLAGS += -DTHEOS_LEAN_AND_MEAN

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk
